# Docs: https://numtide.github.io/devshell

[devshell]
# packages = [ # Search: https://search.nixos.org/packages
#   "curl",
# ]

[[commands]]
package = "rustup"
help = "The Rust toolchain installer"